# Generated by Django 3.2 on 2022-04-01 07:21

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='surname')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=25, verbose_name='gender')),
                ('nationality', models.CharField(blank=True, choices=[('Africa', 'Africa'), ('Australia', 'Australia'), ('Asia', 'Asia'), ('Europe', 'Eeurope'), ('North America', 'North America'), ('South America', 'South America'), ('Greenland', 'Greenland'), ('Antarctica', 'Antarctica')], max_length=255, null=True, verbose_name='nationality')),
                ('profile_image', models.ImageField(blank=True, default='media/profile_images/default.jpg', max_length=255, null=True, upload_to=account.models.get_profile_image_filepath)),
                ('bio', models.TextField(blank=True, null=True)),
                ('github', models.CharField(blank=True, max_length=80, null=True, verbose_name='github')),
                ('stack', models.CharField(blank=True, max_length=80, null=True, verbose_name='stack')),
                ('youtube', models.CharField(blank=True, max_length=80, null=True, verbose_name='youtube')),
                ('insta', models.CharField(blank=True, max_length=80, null=True, verbose_name='insta')),
                ('is_online', models.BooleanField(default=False, verbose_name='is_online')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('accept', models.BooleanField(default=True, verbose_name='accept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility_email', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends'), ('No One', 'No One')], default='No One', max_length=15, verbose_name='visibility_email')),
                ('visibility_timeline', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Friends', max_length=15, verbose_name='visibility_timeline')),
                ('visibility_friend_list', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends'), ('No One', 'No One')], default='Friends', max_length=15, verbose_name='visibility_friend_list')),
                ('visibility_social_links', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends of friends', 'Friends of Friends'), ('Friends', 'Friends'), ('No One', 'No One')], default='Friends', max_length=20, verbose_name='visibility_social_links')),
                ('visibility_featured', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Anyone', max_length=20, verbose_name='visibility_featured')),
                ('visibility_dob', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends'), ('No One', 'No One')], default='No One', max_length=20, verbose_name='visibility_featured')),
                ('visibility_bio', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Friends', max_length=15, verbose_name='visibility_bio')),
                ('visibility_nationality', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends'), ('No One', 'No One')], default='No One', max_length=15, verbose_name='visibility_nationality')),
                ('friendship', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends of friends', 'Friends of Friends'), ('No One', 'No One'), ('Friends', 'Friends')], default='Friends', max_length=20, verbose_name='friendship')),
                ('private_chat_perm', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Friends', max_length=10, verbose_name='private_chat_perm')),
                ('public_chat_perm', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Friends', max_length=10, verbose_name='public_chat_perm')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
