# Generated by Django 3.2 on 2022-04-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='visibility_personal_info',
            field=models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Friends', max_length=15, verbose_name='visibility_personal_info'),
        ),
    ]
