# Generated by Django 3.2 on 2022-04-01 10:31

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountsettings_visibility_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='visibility_gender',
            field=models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends'), ('No One', 'No One')], default='No One', max_length=15, verbose_name='visibility_gender'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', max_length=255, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
