# Generated by Django 3.2 on 2022-04-01 13:26

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220401_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, default='</>', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='account/profile_images/default.jpg', max_length=255, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
