# Generated by Django 3.2 on 2022-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_accountsettings_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='visibility_featured',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='visibility_nationality',
        ),
        migrations.AddField(
            model_name='account',
            name='facebook',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='accept'),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='visibility_dob',
            field=models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends'), ('No One', 'No One')], default='No One', max_length=20, verbose_name='visibility_dob'),
        ),
    ]
