# Generated by Django 3.2 on 2022-04-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='kind',
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Poll', 'Poll'), ('default', 'default')], default='default', max_length=50, verbose_name='content_type'),
        ),
    ]
