# Generated by Django 3.2 on 2022-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220402_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_active',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_obj',
            field=models.BooleanField(blank=True, null=True, verbose_name='reply_obj'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Poll', 'Poll')], default='default', max_length=50, verbose_name='content_type'),
        ),
    ]
