# Generated by Django 3.2 on 2022-04-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_reply_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_obj',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_obj', to='blog.comment'),
        ),
    ]
