# Generated by Django 3.2 on 2022-04-01 07:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, verbose_name='text')),
                ('visibility', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Friends', max_length=100, verbose_name='visibility')),
                ('is_reply', models.BooleanField(default=False, verbose_name='is_reply')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='title')),
                ('kind', models.CharField(choices=[('Post', 'Post'), ('Poll', 'Poll'), ('default', 'default')], default='default', max_length=50, verbose_name='kind')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, size=5)),
                ('text', models.TextField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True, verbose_name='draft')),
                ('visibility', models.CharField(choices=[('Anyone', 'Anyone'), ('Friends', 'Friends')], default='Friends', max_length=100, verbose_name='visibility')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='blog.Comment')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.content', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='comment_replies', to='blog.Comment'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.content')),
                ('votes', models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
